#!/usr/bin/env node
/* ─────────────────────────────────────────────────────────────────────────
   fetch-reviews.mjs — pull live Google reviews AND photos into the site.

   Reviews banner reads assets/js/reviews.data.js; the gallery reads
   assets/js/photos.data.js. This script overwrites both with live data from
   the Google Places API (one Place Details call returns reviews + photos).
   Photos are shown live from Google's own servers with the required credit —
   nothing is downloaded or rehosted.

   YOUR API KEY IS NEVER STORED IN THE PROJECT. This script reads it from an
   environment variable you set in your own shell, so it never lands in the
   code, the git history, or a chat window.

   ── One-time setup ──────────────────────────────────────────────────────
   1. In Google Cloud Console: create an API key and enable "Places API".
   2. (Recommended) Restrict the key — e.g. to your IP for local use.

   ── Each run ────────────────────────────────────────────────────────────
   Set the key for this shell session (do NOT commit it, do NOT paste in chat):

       export GOOGLE_MAPS_API_KEY="your-key-here"

   Then run, passing the business to look up (name + town works well):

       node fetch-reviews.mjs "Park Bistro The Secret Conker, <town>"

   …or pass a known Place ID directly:

       node fetch-reviews.mjs --place-id ChIJ....

   Notes:
   • Google returns up to 5 reviews and you can't choose which.
   • Places Details calls are billable (there's a monthly free tier).
   • Keep the "via Google" attribution in the UI — the terms require it.
   ───────────────────────────────────────────────────────────────────────── */

import { writeFile, readFile } from "node:fs/promises";

// Load a local .env file (KEY=value per line) if present, without overwriting
// anything already set in the shell. Keeps the key out of the code itself.
try {
  const env = await readFile(new URL("./.env", import.meta.url), "utf8");
  for (const line of env.split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
} catch { /* no .env file — that's fine, we'll use the shell env */ }

const KEY = process.env.GOOGLE_MAPS_API_KEY;
if (!KEY) {
  console.error('✗ No API key found. Run:  export GOOGLE_MAPS_API_KEY="your-key"  then re-run this script.');
  process.exit(1);
}

const args = process.argv.slice(2);
let placeId = null;
const pidFlag = args.indexOf("--place-id");
if (pidFlag !== -1) placeId = args[pidFlag + 1];
const query = args.filter((a, i) => a !== "--place-id" && (pidFlag === -1 || i !== pidFlag + 1)).join(" ").trim();

if (!placeId && !query) {
  console.error('✗ Tell me what to look up:  node fetch-reviews.mjs "Business name, town"');
  process.exit(1);
}

const api = (path, params) => {
  const u = new URL("https://maps.googleapis.com/maps/api/place/" + path);
  Object.entries({ ...params, key: KEY }).forEach(([k, v]) => u.searchParams.set(k, v));
  return fetch(u).then((r) => r.json());
};

try {
  if (!placeId) {
    console.log(`→ Finding place for "${query}"…`);
    const find = await api("findplacefromtext/json", {
      input: query, inputtype: "textquery", fields: "place_id,name",
    });
    if (find.status !== "OK" || !find.candidates?.length) {
      throw new Error(`Place lookup failed: ${find.status} ${find.error_message || ""}`);
    }
    placeId = find.candidates[0].place_id;
    console.log(`→ Matched: ${find.candidates[0].name} (${placeId})`);
  }

  console.log("→ Fetching reviews + photos…");
  const details = await api("details/json", {
    place_id: placeId,
    fields: "name,rating,user_ratings_total,reviews,photos",
    reviews_sort: "most_relevant",
    language: "en",
  });
  if (details.status !== "OK") {
    throw new Error(`Details failed: ${details.status} ${details.error_message || ""}`);
  }

  const d = details.result;

  /* ── reviews ─────────────────────────────────────────────────────────── */
  const reviews = (d.reviews || []).map((r) => ({
    name: r.author_name,
    rating: r.rating,
    when: r.relative_time_description,
    text: r.text,
  }));

  if (reviews.length) {
    const out =
`/* Live Google reviews — generated by fetch-reviews.mjs on ${new Date().toISOString()}.
   Do not edit by hand; re-run the script to refresh. Keep the "via Google"
   attribution in the UI as required by the Google Places API terms. */
window.__REVIEWS__ = ${JSON.stringify(
      { source: "google", rating: d.rating ?? null, total: d.user_ratings_total ?? null, items: reviews },
      null, 2,
    )};
`;
    await writeFile(new URL("./assets/js/reviews.data.js", import.meta.url), out);
    console.log(`✓ Wrote ${reviews.length} review(s) → assets/js/reviews.data.js`);
  } else {
    console.warn("⚠ No reviews returned — left placeholder reviews in place.");
  }

  /* ── photos ──────────────────────────────────────────────────────────── */
  // Resolve each photo_reference to Google's own hosted image URL. We follow the
  // Place Photo redirect and keep only the final URL — the image is never stored
  // by us, and the API key never lands in the page (it stays in this script).
  const resolvePhoto = async (ref) => {
    const u = new URL("https://maps.googleapis.com/maps/api/place/photo");
    u.searchParams.set("maxwidth", "1200");
    u.searchParams.set("photo_reference", ref);
    u.searchParams.set("key", KEY);
    const res = await fetch(u, { redirect: "manual" });
    return res.headers.get("location"); // Google-hosted, keyless image URL
  };

  const rawPhotos = (d.photos || []).slice(0, 8);
  const photos = [];
  for (const p of rawPhotos) {
    try {
      const url = await resolvePhoto(p.photo_reference);
      if (url) photos.push({ url, attribution: (p.html_attributions || []).join(" · ") });
    } catch { /* skip a photo that won't resolve */ }
  }

  if (photos.length) {
    const out =
`/* Live Google Places photos — generated by fetch-reviews.mjs on ${new Date().toISOString()}.
   'url' points at Google's own hosted copy (nothing is stored here) and
   'attribution' is the contributor credit Google requires you to display.
   These URLs can change over time — re-run the script to refresh. */
window.__PHOTOS__ = ${JSON.stringify({ source: "google", items: photos }, null, 2)};
`;
    await writeFile(new URL("./assets/js/photos.data.js", import.meta.url), out);
    console.log(`✓ Wrote ${photos.length} photo(s) → assets/js/photos.data.js`);
  } else {
    console.warn("⚠ No photos returned — left placeholder photos in place.");
  }

  if (!reviews.length && !photos.length) {
    console.warn(`Nothing to update for "${d.name}".`);
  } else {
    console.log(`✓ Done for "${d.name}". Refresh the page to see it.`);
  }
} catch (err) {
  console.error("✗ " + err.message);
  process.exit(1);
}
